export enum OperationType {
    TEXT_INSERT = 'TEXT_INSERT',
    TEXT_DELETE = 'TEXT_DELETE',
    TEXT_FORMAT = 'TEXT_FORMAT',
    CITATION_INSERT = 'CITATION_INSERT',
    CITATION_UPDATE = 'CITATION_UPDATE',
    CITATION_DELETE = 'CITATION_DELETE',
    CURSOR_MOVE = 'CURSOR_MOVE'
}